### ISSUE TITLE
Feature request: define custom extra registry

### ISSUE THREAD

**Issue by Kintaro** [fosskers/vend#16]
For some internal projects or other use-cases, one could manually download and update dependencies when needed, but it might be a nicer use-case if there were a way to define a custom list of dependencies and sources if needed. Similar to say how ASDF allows defining source registries. 

That way, the same tooling can be used for not-yet onboarded dependencies without having to make a PR or clone of the tool. 
This might add a small bit of additional complexity, but I'd be willing to give that a shot. Just want to make sure it's needed before working on it.

**Comment by fosskers** [comment]
Let me think about the lightest way to enable this.

**Comment by fosskers** [comment]
A low-tech solution would be to have a `registry` file within your project of the format:
```
foo https://github.com/secret-org/secret-project-foo
bar https://github.com/secret-org/secret-project-bar
```
but, I wouldn't want to have to deprecate this format if later I introduce `vend.toml` for other configuration. In a TOML file it would instead look like:
```toml
[registry]
foo = "https://github.com/secret-org/secret-project-foo"
bar = "https://github.com/secret-org/secret-project-bar"
```

Thoughts?
